# Generated by Django 5.0.7 on 2024-08-22 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=datetime.datetime(2024, 8, 22, 22, 16, 27, 603958, tzinfo=datetime.timezone.utc)),
        ),
    ]
